config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'all_link' => 'progates#all_link'
  get 'htmlcss_first' => 'progates#first'
  get 'htmlcss_second' => 'progates#second'
  get 'java' => 'progates#java'
  get 'java_part2' => 'progates#java_part2'
  get 'java_part3' => 'progates#java_part3'
  get 'java_part4' => 'progates#java_part4'
  get 'java_advance_part2' => 'progates#java_advance_part2'
  get 'java_part5' => 'progates#java_part5'

  get 'ruby' => 'progates#ruby'
  get 'ruby_part2' => 'progates#ruby_part2'
  get 'ruby_part3' => 'progates#ruby_part3'
  get 'ruby_part4' => 'progates#ruby_part4'
  get 'ruby_part5' => 'progates#ruby_part5'

  get 'progate_php' => 'progates#php'
  get 'progate_php_part2' => 'progates#php_part2'


  get 'csharp' => 'paiza#csharp'
  get 'csharp_part2' => 'paiza#csharp_part2'
  get 'csharp_part3' => 'paiza#csharp_part3'
  get 'csharp_part4' => 'paiza#csharp_part4'
  get 'csharp_part5' => 'paiza#csharp_part5'
  get 'csharp_part6' => 'paiza#csharp_part6'

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/paiza_controller.rb
class PaizaController < ApplicationController

	def csharp
	end

	def csharp_part2
	end

	def csharp_part3
	end

	def csharp_part4
	end

	def csharp_part5
	end

	def csharp_part6
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/progates_controller.rb
class ProgatesController < ApplicationController

	def all_link
	end

	def first
	end

	def second
	end

	def java
	end

	def java_part2
	end

	def java_part3
	end

	def java_part4
	end

	def java_advance_part2
	end

	def java_part5
	end

	def ruby
	end

	def ruby_part2
	end

	def ruby_part3
	end

	def ruby_part4
	end

	def ruby_part5
	end

	def php
	end

	def php_part2
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paiza_helper.rb
module PaizaHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/progates_helper.rb
module ProgatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeAugust</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paiza/csharp_part5.html.erb
<div style="padding: 20px 0 20px 0;">
	Home→<%= link_to 'Home', root_path %>
	first→<%= link_to 'Paiza/C#コース1', csharp_path %>
	prev→<%= link_to 'Paiza/C#コース4', csharp_part4_path %>
</div>

<h1>Paiza C#コース5　C#入門編5: 多次元配列を理解しよう</h1>


<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/2次元配列の概要.mp4" controls preload muted></video><br>
	＃01:2次元配列の概要
	2つのインデックスで要素を指定する2次元配列について、基本的な考え方を学習しましょう。2次元配列を使うと、複雑なデータを操作できるようになります。
	①2次元配列とは
	2次元配列とは、2つのインデックスで要素を指定する配列のこと。
	例えば、
	arr[3][4] = 100;
	とすると、インデックス 3, 4 に対応する要素に、100を代入できる。
	②多次元配列の用途
	- RPGのマップ
	- 写真・イラストなどのイメージ
	- 3D-CGの空間座標
	- ゲームの盤面
	- 表形式データ
	など
	③ 参考になるWebページ
	配列 - C# によるプログラミング入門 | ++C++; // 未確認飛行 C
	https://ufcpp.net/study/csharp/st_array.html
	配列 (C# プログラミング ガイド) - Microsoft Docs
	https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/arrays/index

	
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>

<div style="padding: 100px 0 100px 0;">
	<video src="assets/videos/コメントでプログラムを見やすく！.mp4" controls preload muted></video><br>
</div>


<div style="padding: 100px 0 100px 0;">
next→<%= link_to 'Paiza/C#コース6', csharp_part6_path %><br>
Home→<%= link_to 'Home', root_path %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<%= link_to 'ページ一覧', all_link_path %>

<%= link_to 'Progate/HTML&CSS初級編', htmlcss_first_path %>

<%= link_to 'Progate/Java コース1', java_path %>

<%= link_to 'Progate/Ruby コース1', ruby_path %>

<%= link_to 'Progate/PHP コース1', :controller => 'progates', :action => 'php' %>

<%= link_to 'Paiza/C#コース1', csharp_path %>




Google Cloud Vision APIを使って、食品パッケージ画像からテキストを非同期で読み取りフォームに記載してみる(コメントアウトで記載)<br>
<!-- Rails
jQuery
GoogleCloudVisionAPI
概要
ポートフォリオでGoogle Cloud Vision APIを使ってみたので紹介したいと思います。
ちなみに食品パッケージのサンプルは世界一おいしいアマタケのサラダチキン(ピザ味)を使用してます

Image from Gyazo

詳細
下準備
詳細は省きますが、Cloud Vision API を利用するため GCP のサービスアカウントの json ファイルをダウンロードします。gem 'google-cloud-vision'も bundle installしてください。keyファイルのPathはcredentials.yml.encで管理しました。
（時間が空いたときに詳細手順を記載します...）
参考:RailsにGoogle Cloud Vision APIを導入し、簡単に過激な画像を検知する

各種ファイルの作成
ルート
本件に関係あるものは、post "upload" だけです

route.rb
  resources :foods, only: %i[index show new create] do
    collection do
      get "search"
      post "upload"
    end
ビュー
3行目のinput行で発火させます。

views/foods/new.html.haml
= form_with model: @food , data: { remote: false }, class: "common-form" do |food|
  .common-form__upload-image
    %input#image-upload.common-form__upload-image--input{name: "image", type: "file"}
    %label.common-form__image--icon{for: "image-upload"}
      .common-form__upload-image--icon-wrap
        %i.fas.fa-image
        .common-form__upload-image--icon-text 画像からPFCを取得する
  #~中略~
  .plan-form__pfc
    .plan-form__pfc--protein
      = food.number_field :protein, step:"0.1", min:0
      = food.label 'たんぱく質(g)'
      .plan-form__pfc--protein--description 画像を挿入すると自動で数値が入力されます。
    .plan-form__pfc--fat
      = food.number_field :fat, step:"0.1", min:0
      = food.label '脂質(g)'
      .plan-form__pfc--fat--description 画像を挿入すると自動で数値が入力されます。
    .plan-form__pfc--carbo
      = food.number_field :carbo, step:"0.1", min:0
      = food.label '炭水化物(g)'
      .plan-form__pfc--carbo--description 画像を挿入すると自動で数値が入力されます。
  #~後略~
jQuery
FormDataでコントローラーに送信します。
formData.append("image",$('input[type=file]')[0].files[0]);
が個人的に気づきにくかったところです。
こうすることで後述のコントローラーでデータを受け取れます。

upload.js
$(function(){
  if(document.URL.match(/\/foods\/new/)) {
 //~中略~
    $(document).on('change', 'input[type= "file"]',function(e) {
 //~中略~
      e.preventDefault();
      var formData = new FormData();
      formData.append("image",$('input[type=file]')[0].files[0]);
      $.ajax({
        type:'POST',
        url: '/foods/upload',
        data: formData,
        dataType:'json',
        processData: false,
        contentType: false
      })
 //~後略~
    })
  }
})
コントローラー
image = params[:image].pathでjQuery側で設定したformDataを受け取れます。
正規表現で抽出した文字列を加工してます。1例なので、食品パッケージのバリエーションの種類分作る必要があります。(まだやってない...)

foods_controller.rb
class FoodsController < ApplicationController
#~中略~
  def upload
    require 'google/cloud/vision'
    ENV["GOOGLE_CLOUD_PROJECT"] = Rails.application.credentials.google[:GOOGLE_CLOUD_PROJECT]
    ENV["GOOGLE_CLOUD_KEYFILE"] = if Rails.env.production?
                                    Rails.application.credentials.google[:GOOGLE_CLOUD_KEYFILE_PRO]
                                  else
                                    Rails.application.credentials.google[:GOOGLE_CLOUD_KEYFILE_DEV]
                                  end
    image = params[:image].path
    image_annotator_client = Google::Cloud::Vision::ImageAnnotator.new
    image_text = (image_annotator_client.document_text_detection image: image).to_s
    if image_text.include?("たんぱく質")
      @protein = image_text[/たんぱく質(.{0,3}\d+\.?\d+)/][/\d+\.?\d+/].to_f
      @fat = image_text[/脂質(.{0,3}\d+\.?\d+)/][/\d+\.?\d+/].to_f
      @carbo = image_text[/炭水化物(.{0,3}\d+\.?\d+)/][/\d+\.?\d+/].to_f
      @data = { protein: @protein, fat: @fat, carbo: @carbo }
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

#~後略~

json.jbuilder
上記のコントローラーで処理したデータをjQueryで使えるようにします。

upload.json.jbuilder
json.data do |data|
  data.protein @data[:protein]
  data.fat @data[:fat]
  data.carbo @data[:carbo]
end
jQuery
再度jQueryファイルに戻ります。
data.data.protein等にするとデータを取り出せます。

upload.js
$(function(){
  if(document.URL.match(/\/foods\/new/)) {
 //~中略~
    $(document).on('change', 'input[type= "file"]',function(e) {
 //~中略~
      e.preventDefault();
      var formData = new FormData();
      formData.append("image",$('input[type=file]')[0].files[0]);
      $.ajax({
        type:'POST',
        url: '/foods/upload',
        data: formData,
        dataType:'json',
        processData: false,
        contentType: false
      })
      .done(function(data){
        $('#food_protein').val(data.data.protein)
        $('#food_fat').val(data.data.fat)
        $('#food_carbo').val(data.data.carbo)
        alert(`画像の読み込みに成功しました! たんぱく質:${data.data.protein}g 脂質:${data.data.fat}g 炭水化物:${data.data.carbo}g`)
      })
      .fail(function(){
        alert('画像の読み込みに失敗しました')
      })
    })
  }
})
完成です -->

<div style="padding: 100px 0 100px 0;">
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/progates/all_link.html.erb
<div style="padding: 20px 0 20px 0;">
	Home→<%= link_to 'Home', root_path %>
</div>

<h1>ページ一覧</h1>

<div style="padding: 100px 0 100px 0;">
<%= link_to 'Progate/HTML&CSS初級編', htmlcss_first_path %>

<%= link_to 'Progate/Java コース1', java_path %>
<%= link_to 'Progate/Java コース2', java_part2_path %>
<%= link_to 'Progate/Java コース3', java_part3_path %>
<%= link_to 'Progate/Java コース4', java_part4_path %>
<%= link_to 'Progate/Java道場コース2', java_advance_part2_path %><br>
<%= link_to 'Progate/Java コース5', java_part5_path %>
<%= link_to 'Progate/Rubyコース1', ruby_path %>
<%= link_to 'Progate/Rubyコース2', ruby_part2_path %>
<%= link_to 'Progate/Rubyコース3', ruby_part3_path %>
<%= link_to 'Progate/Rubyコース4', ruby_part4_path %>
<%= link_to 'Progate/Rubyコース5', ruby_part5_path %><br>
<%= link_to 'Progate/PHP コース1', :controller => 'progates', :action => 'php' %>


<%= link_to 'Paiza/C#コース1', :controller => 'paiza', :action => 'csharp' %>  <!-- controller, actionを定義したらルートは二重になるためカット -->
<%= link_to 'Paiza/C#コース2', csharp_part2_path %>
<%= link_to 'Paiza/C#コース3', :controller => 'paiza', :action => 'csharp_part3' %>
<%= link_to 'Paiza/C#コース4', :controller => 'paiza', :action => 'csharp_part4' %>
<%= link_to 'Paiza/C#コース5', :controller => 'paiza', :action => 'csharp_part5' %>

</div>

app/views/progates/first.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Progate/HTML&CSS初級編', htmlcss_first_path %>
<%= link_to 'Progate/HTML&CSS中級編', htmlcss_second_path %>


<!-- 文字の大きさ -->
<div style="padding: 100px 0 100px 0;">
<!-- <h1>要素で囲んでください -->
<h1>プログラミングの世界へようこそ</h1>
<!-- <h2>要素で囲んでください -->
<h2>Progateとは</h2>
<!-- <p>要素で囲んでください -->
<p>オンラインのプログラミング学習サービスです</p>
</div>


<!-- リンク作成 -->
<div style="padding: 100px 0 100px 0;">
<!-- https://prog-8.comへのリンクを作成してください -->
<a href="https://prog-8.com">Progateへ</a>
<!-- https://google.comへのリンクを作成してください -->
<a href="https://google.com">Googleへ</a>
</div>


<!-- 画像表示 -->
<div style="padding: 100px 0 100px 0;">
  <!-- リンク先の画像を表示してください -->
<img src="https://prog-8.com/images/html/beginner/wanko.jpg">
<!-- リンク先の画像を表示してください　周りのスペースも確保 -->
<img src="https://prog-8.com/images/html/beginner/school.jpg" style="margin: 100px;">
</div>


<!-- リストなどの作成 -->
<div style="padding: 100px 0 100px 0;">
<ul>
  <li>html</li>
  <li>php</li>
  <li>ruby</li>
</ul>
<!-- olは数字を先頭につける -->
</div>


<!-- css -->
<div style="padding: 100px 0 100px 0;" class="css_create">
  <h1>Hello World</h1>
  <p>プログラミングの世界へようこそ</p>
</div>


<!-- サイズ、背景色 -->
<div style="padding: 100px 0 100px 0;" class="css2">
  <h1>Hello World</h1>
  <img src="https://prog-8.com/images/html/beginner/school.jpg">
</div>


<!-- タグに名前をつける -->
<div style="padding: 100px 0 100px 0;">
  <h2>レッスン一覧</h2>
  <ul>
    <!-- 1つ目の<li>要素にselectedというclassを与えてください -->
    <li class="selected">HTML</li>
    <li>PHP</li>
    <li>Ruby</li>
  </ul>
</div>


<!-- htmlの構造 -->
<div style="padding: 100px 0 100px 0;">
  <!-- DOCTYPE宣言を追加してください -->
  <!DOCTYPE html>
  <!-- <html>要素を追加してください -->
    <html>
      <head>
      </head>
      <body>
        <div class="fontchange">
          はろわAvenir Next
        </div>
      </body>
    </html>
</div>


<!-- headの設定 -->
<div style="padding: 100px 0 100px 0;">
  <!DOCTYPE html>
  <html>
    <head>
      <!-- 雛形をコピーして、3つの要素を追加してください -->
      <meta charset="utf-8"><!--文字化け防ぐ-->
      <title>Progate</title><!--タイトル-->
      <link rel="stylesheet" href="stylesheet.css"><!--css読み込み-->
    </head>
    <body>
      <!-- <div>要素を追加し、「header」というclassをつけてください -->
      <div class="header">
        <!-- <div>要素を追加し、「header-logo」というclassをつけてください -->
        <div class="header-logo">
          Progate
        </div>
        <!-- <div>要素を追加し、「header-list」というclassをつけてください -->
        <div class="header-list">
          <ul>
            <li>プログラミングとは</li>
            <li>学べるレッスン</li>
            <li>お問い合わせ</li>
          </ul>
        </div>
      </div>


      <!-- <div>要素を追加し、「main」というclassをつけてください -->
      <div class="main">
        <!-- <div>要素を追加し、「copy-container」というclassをつけてください -->
        <div class="copy-container">
          <h1>HELLO WORLD<span>.</span></h1>
          <h2>プログラミングの世界へようこそ</h2>
        </div>
        <!-- <div>要素を追加し、「contents」というclassをつけてください -->
        <div class="contents">
          <!-- <h3>要素を追加してください -->
          <h3 class="section-title">学べるレッスン</h3>
          <!-- <div>要素を追加し、「contents-item」というclassをつけてください -->
          <div class="contents-item">
            <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/html.svg" alt="" />
            <p>HTML & CSS</p>
          </div>
          <!-- <div>要素を追加し、「contents-item」というclassをつけてください -->
          <div class="contents-item">
            <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/php.svg" alt="" />
            <p>PHP</p>
          </div>
          <!-- <div>要素を追加し、「contents-item」というclassをつけてください -->
          <div class="contents-item">
            <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/ruby.svg" alt="" />
            <p>Ruby</p>
          </div>
          <!-- <div>要素を追加し、「contents-item」というclassをつけてください -->
          <div class="">
            <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/study/swift.svg" alt="" />
            <p>Swift</p>
          </div>
        </div>
        <!-- <div>要素を追加し、「contact-form」というclassをつけてください -->
        <div class="contact-form">
          <h3 class="section-title">お問い合わせ</h3>
          <p>メールアドレス（必須）</p>
          <!-- <input>要素を追加してください -->
          <input>
          <p>お問い合わせ内容（必須）</p>
          <!-- <textarea>要素を追加してください -->
          <textarea></textarea>
          <p>※必須項目は必ずご入力ください</p>
          <!-- <input>要素を追加してください -->
          <input class="contact-submit" type="submit" value="送信">
        </div>
      </div>


      <!-- <div>要素を追加し、「footer」というclassをつけてください -->
      <div class="footer">
        <!-- <div>要素を追加し、「footer-logo」というclassをつけてください -->
        <div class="footer-logo">
          Progate
        </div>
        <!-- <div>要素を追加し、「footer-list」というclassをつけてください -->
        <div class="footer-list">
          <ul>
            <li>会社概要</li>
            <li>採用</li>
            <li>お問い合わせ</li>
          </ul>
        </div>
      </div>
    </body>
  </html>
</div>


<!--  -->
<div style="padding: 100px 0 100px 0;">
</div>


<div style="padding: 100px 0 100px 0;">
</div>


<div style="padding: 100px 0 100px 0;">
</div>

app/views/progates/second.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Progate</title>
    <link rel="stylesheet" href="stylesheet.css">
  </head>
  <body>
    <!-- ここにコードを書いていきましょう -->
    <header>
      
    </header>
    <div class="top-wrapper">
      
    </div>
    <div class="lesson-wrapper">
      
    </div>
    <div class="message-wrapper">
      
    </div>
    <footer>
      
    </footer>
  </body>
</html>